// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt8lIAsKuZZ9NO7XTNriCI_vHLc5QDTg8',
    appId: '1:301252366517:web:a7791635fcf57e3a6beefc',
    messagingSenderId: '301252366517',
    projectId: 'flutter-stayinn',
    authDomain: 'flutter-stayinn.firebaseapp.com',
    storageBucket: 'flutter-stayinn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqEKxxlXDkUzLHzJz3gMpoS2f91tmVu4Y',
    appId: '1:301252366517:android:262ffa8e117fe5826beefc',
    messagingSenderId: '301252366517',
    projectId: 'flutter-stayinn',
    storageBucket: 'flutter-stayinn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS3XF0CBcO9hfpHK80zXzDSbKfRJ-tCmA',
    appId: '1:301252366517:ios:785f19bd90cdb6216beefc',
    messagingSenderId: '301252366517',
    projectId: 'flutter-stayinn',
    storageBucket: 'flutter-stayinn.appspot.com',
    iosBundleId: 'com.example.flutterStay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS3XF0CBcO9hfpHK80zXzDSbKfRJ-tCmA',
    appId: '1:301252366517:ios:bd9322f845e644366beefc',
    messagingSenderId: '301252366517',
    projectId: 'flutter-stayinn',
    storageBucket: 'flutter-stayinn.appspot.com',
    iosBundleId: 'com.example.flutterStay.RunnerTests',
  );
}
